apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: hifi-liquidator-js
  name: hifi-liquidator-js
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hifi-liquidator-js
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      labels:
        io.kompose.service: hifi-liquidator-js
    spec:
      containers:
        - env:
            - name: ALCHEMY_KEY
              valueFrom:
                secretKeyRef:
                  name: hifi-liquidator-js-secret
                  key: alchemy-key
            - name: INFURA_KEY
              valueFrom:
                secretKeyRef:
                  name: hifi-liquidator-js-secret
                  key: infura-key
            - name: NETWORK_NAME
              valueFrom:
                configMapKeyRef:
                  name: hifi-liquidator-js-config-map
                  key: network-name
            - name: PERSISTENCE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: hifi-liquidator-js-config-map
                  key: persistence-enabled
            - name: SELECTED_ACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: hifi-liquidator-js-config-map
                  key: selected-account
            - name: SELECTED_STRATEGY
              valueFrom:
                configMapKeyRef:
                  name: hifi-liquidator-js-config-map
                  key: selected-strategy
            - name: WALLET_SEED
              valueFrom:
                secretKeyRef:
                  name: hifi-liquidator-js-secret
                  key: wallet-seed
          image: hififinance/hifi-liquidator-js:1.0.5
          name: hifi-liquidator-js
          resources:
            limits:
              cpu: "0.1"
              memory: 128Mi
            requests:
              cpu: "0.01"
              memory: 64Mi
          volumeMounts:
            - mountPath: /liquidator/cache
              name: cache
      restartPolicy: Always
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: cache
status: {}
