version: "3"
services:
  hifi-liquidator-js:
    build: .
    environment:
      ALCHEMY_KEY: $ALCHEMY_KEY
      INFURA_KEY: $INFURA_KEY
      NETWORK_NAME: ${NETWORK_NAME:-homestead}
      PERSISTENCE_ENABLED: ${PERSISTENCE_ENABLED:-true}
      SELECTED_ACCOUNT: ${SELECTED_ACCOUNT:-0}
      SELECTED_STRATEGY: ${SELECTED_STRATEGY:-uniswap-v2}
      WALLET_SEED: $WALLET_SEED
    volumes:
      - db:/bot/db
volumes:
  db:
